# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.date_time_normalizer:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        public: false
        tags:
            - {name: serializer.normalizer}

    app.reflection_extractor:
        class: Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor
        scope: prototype
        public: false

    app.object_normalizer:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        public: false
        arguments: [null, null, null, "@app.reflection_extractor"]
        tags:
            - {name: serializer.normalizer}

    json_encoder:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
        public: false
        tags:
            - {name: serializer.encoder}
